### ISSUE TITLE
Gepris data pipeline:

### ISSUE THREAD

**Issue by jessebenjamin** [FUB-HCC/IKON-backend#1]
- [x] map country names in German to country names in English that are used in topojson (e.g. ISO names)

**Comment by wittenator** [comment]
@polyphem Do you know about the python script I wrote?

**Comment by wittenator** [comment]
I think it would be cool, if we would have something like a data loader in our node.js server which transforms datasets on start-up into the json structure and saves it locally, but keeps a version cached in order to serve it more quickly. What do you think, @polyphem ?

**Comment by jessebenjamin** [comment]
this is great, but please work on issues as sorted in the backlog @wittenator @polyphem @simon991

**Comment by jessebenjamin** [comment]
this is great, but please work on issues as sorted in the backlog @wittenator @polyphem @simon991

**Comment by wittenator** [comment]
Had to prepare a base for that for the geocoding in 4341a00edd7d829766637ecec25ba2015aca5a0a. That could serve as a base (and needs some cleanup).

**Comment by wittenator** [comment]
@mingtung That is probably not necessary anymore if we are able to get the ISO names of the German country names, right?

**Comment by mingtung** [comment]
Yes, as long as we can map the German country names on map!

**Comment by mingtung** [comment]
close the ticket. Duplicated with https://github.com/FUB-HCC/IKON-backend/issues/3
