### ISSUE TITLE
CircleCI problem

### ISSUE THREAD

**Issue by ckinkeldey** [FUB-HCC/IKON-backend#113]
Branches cannot be merged at the moment because of CircleCI error

**Comment by wittenator** [comment]
Since we needed to change the whole secret delivery process quite hastily, I didn't have time to adapt the CitcleCI process to that. Since we do not have real tests ATM anyways, I am going to deactivate the necessary CI flag for now until we integrated and switched to GitHub Actions.

**Comment by ckinkeldey** [comment]
OK, desactivate it for now.
