### ISSUE TITLE
Fix notebook

### ISSUE THREAD

**Issue by ckinkeldey** [FUB-HCC/IKON-backend#117]
**Describe the bug**
Cell 3 (SQL):
UndefinedFunction: function first(text) does not exist
LINE 1: SELECT FIRST(project_abstract), FIRST(id), FIRST(title)     ...
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

**-> new postgres version?**

**To Reproduce**
Run notebook

**Expected behavior**
no errors

**Screenshots**
![Screenshot 2019-11-05 18 14 55](https://user-images.githubusercontent.com/3234376/68229806-30f75a80-fff8-11e9-92f1-c6b5f45dd494.png)

**Comment by ckinkeldey** [comment]
cell 3 works, but cell 5 does not (empty summary?)
![Screenshot 2019-11-06 15 00 32](https://user-images.githubusercontent.com/3234376/68304626-6f4b5300-00a6-11ea-800e-373b0a73c0ed.png)

**Comment by wittenator** [comment]
Did you verify that projects exist in the mfnprojects table?

**Comment by wittenator** [comment]
*bump*

**Comment by ckinkeldey** [comment]
I have a dependency issue with keras now (master branch):
![Screenshot 2019-11-21 11 58 20](https://user-images.githubusercontent.com/3234376/69332385-df390c00-0c56-11ea-8c1d-094c64e7a5af.png)

**Comment by wittenator** [comment]
Since I am going to rework the autoencoder either way, you can just skip these cells.

**Comment by ckinkeldey** [comment]
OK, I commented out the autoencoder and the related plots. Now it works thanks!
