### ISSUE TITLE
Frontend installation: docker multistagebuild solution

### ISSUE THREAD

**Issue by ckinkeldey** [FUB-HCC/IKON-backend#121]

**Comment by lillijo** [comment]
Can you add description for frontend building to readme? (npm run-scripts build ) or add it to the initial script or maybe even find another solution that npm is not necessary? @wittenator

**Comment by wittenator** [comment]
Please have a look at the referenced pull request. I've added a front end build step to the Controller container.

**Comment by lillijo** [comment]
ah didnt see alright :)
