### ISSUE TITLE
Adding error handling for DAL requests

### ISSUE THREAD

**Issue by wittenator** [FUB-HCC/IKON-backend#123]
**Is your feature request related to a problem? Please describe.**
The requests in the DAL service do not throw an error when the MWC is not working

**Describe the solution you'd like**
Please add proper error handling for these routes.

**Additional context**
This is important for proper monitoring of the network.

**Comment by lillijo** [comment]
do you mean the GETs and PATCHes should throw errors in the command line or how do you mean it?

**Comment by wittenator** [comment]
There should be exceptions thrown when the requests fail (especially the PATCH requests), which the service catches and logs. This is important since I'll add an unified log service later which will use that.

**Comment by lillijo** [comment]
maybe i am getting something wrong but the dal already throws errors for patch in the dal log when e.g. the password for mwc is wrong?

**Comment by wittenator** [comment]
The last time I checked (when the VIA password changed), the DAL service failed the Patch requests silently. I'm going to check in this again
