### ISSUE TITLE
Add request for "missing" research projects

### ISSUE THREAD

**Issue by ckinkeldey** [FUB-HCC/IKON-backend#135]
We need a request that returns all research projects that do NOT have the status "Freigegeben" BUT have time data

**Comment by lillijo** [comment]
not all data is needed of those projects.
Preferably something like this: 
{
    id: projectidentifier, 
    years: [funding_start_year,...., funding_end_year],
    forschungsbereich: projectForschungsbereich
}

**Comment by jessebenjamin** [comment]
i dont think you need forschungsbereich even: most of the recently added will not have those anyway, and currently we will display them as a grey area anyway! so no need to tie it to anything!

**Comment by wittenator** [comment]
Solved in #153
