### ISSUE TITLE
Enrich Data from GEPRIS

### ISSUE THREAD

**Issue by polyphem** [FUB-HCC/IKON-backend#14]
- [x] add Fachkollegium
- [x] add Fach
- [x] check Hauptthemen in current data – is it really only six?

**Comment by wittenator** [comment]
As far as I saw both fields "Fach" and "Fachkollegium" are already present in the dataset. They are called "subject_area" and "review_board". Do I miss something on this one?
We probably have a mismatch between the German names and the English terms. Could you explain what "Hauptthemen" would be in the scope of the current dataset (which get generated from the GEPRIS scrapes)?

**Comment by wittenator** [comment]
I assume that this ticket is resolved.
