### ISSUE TITLE
Frontend requirements and bugs for backend

### ISSUE THREAD

**Issue by lillijo** [FUB-HCC/IKON-backend#158]
- [x] there should be no null Values (eg Sammlung in 150042)
- [x] "exists" and "namespace" not needed
- [x] Projektleitung is always empty. is this in the data or error?
- [x] Clustering and ordering of projects is weird
- [x] change mappoints like: 
const minX = Math.min(projects.map(c => c.mappoint[0]));
const minY = Math.min(projects.map(c => c.mappoint[1]));
  return projects.map(p => {
      mappoint: [p.mappoint[0] - minX, p.mappoint[1] - minY]})
- [x] I also need the property "HatGeographischeVerschlagwortung" (actually just the continents woud be best)

... for now

- [x] another thing that we still have to discuss with everyone: Shall formats be included in the final prototype? if so I need to have them with ids and connections similar to targetgroups as well.

**Comment by wittenator** [comment]
Additionally, I only insert timestamps in the ```timeframe``` attribute of each project.
