### ISSUE TITLE
Geographical data preparation for first visualization prototype:

### ISSUE THREAD

**Issue by mingtung** [FUB-HCC/IKON-backend#2]
- [x] convert address to lon/lat coordinates
- [x] find low-resolution GEOJSON for country hulls (for international_connections)
- [x] enrich project JSON by lon/lat coordinates

**Comment by simon991** [comment]
I did some work on the projector. Maybe it helps you with this task. I documented it here:
- [https://intern.hcc.mi.fu-berlin.de/confluence/display/IKON/Geo+View+for+IKON-projector](https://intern.hcc.mi.fu-berlin.de/confluence/display/IKON/Geo+View+for+IKON-projector)

-  [https://github.com/FUB-HCC/IKON-projektor/compare/geo-visualization](https://github.com/FUB-HCC/IKON-projektor/compare/geo-visualization)

**Comment by wittenator** [comment]
Looks good! Since you have a better idea of what you need: What kind of information do you need for the GeoView visualisation? Which data structure do you prefer? (I suppose that we give the frontend the GeoJSON/TOPOJSON data as static assets.)

**Comment by simon991** [comment]
At the moment I am rendering the map from an imaginary Array of institutions with the following structure. So for the real dataset, we need the coordinates for the single institutions as well as a standardized (e.g. ISO_A3) representation for their corresponding research areas.
```javascript
const sampleInstitutions = [
    { name: 'Tokyo',
      coordinates: [139.6917, 35.6895],
      numberProjects: 378,
      researchAreas: [ // Country codes as ISO_A3
          {area: 'STP', number: 150},
          {area: 'EGY', number: 228},
    ]},
    { name: 'Jakarta',
      coordinates: [106.8650, -6.1751],
      numberProjects: 305,
      researchAreas: [ // Country codes as ISO_A3
          {area: 'RUS', number: 100},
          {area: 'SOM', number: 200},
          {area: 'CAF', number: 5}
    ]},
    ....
```
