### ISSUE TITLE
Incorrect bot credentials

### ISSUE THREAD

**Issue by wittenator** [FUB-HCC/IKON-backend#26]
Hi Alvaro,

I tried to access the API via the bot credentials but apparently the password is wrong. Could you check if there is a mistake? (My SHK credentials work. I verified that.)

Sincerely,
Tim

**Comment by alvarosaurus** [comment]
Please follow the instructions on the confluence page and send me the error message you are getting, together with the exact time you accessed the site, so I can check in the logs what's going on.

cheers
alvaro

Edited 27.11.2018: in case you are trying to login to the UI using bot credentials, that won't work.
