### ISSUE TITLE
Simulate WTAs

### ISSUE THREAD

**Issue by jessebenjamin** [FUB-HCC/IKON-backend#34]
- [x] API Query for WTA
- [x] Simulate according to attributes
- [x] Add links to actual projects
- [x] Simulate for scenario:

- Pflichtangaben (Titel, Initiative, Format, Zielgruppe) sind ausgefüllt 
- es gibt 0-1 Verbindungen zu Drittmittel-Projekten
- bei einer Projektverbindung werden 1:1 die freien Schlagwörter des Projektes übernommen

**Comment by wittenator** [comment]
FYI: I am not going to build a Query for the WTAs at the moment, simply because the structure of the articles may change until June.
