### ISSUE TITLE
Host the latest version of the backend 

### ISSUE THREAD

**Issue by ckinkeldey** [FUB-HCC/IKON-backend#36]
Since the prototype does not run at the museum we need to install it ourselves on http://ikon-research.imp.fu-berlin.de/
We have access to:
https://github.com
docker.pkg.github.com (http / https)
https://via.naturkundemuseum.berlin
https://nominatim.openstreetmap.org

**Comment by wittenator** [comment]
I integrated a CI/CD pipeline using CircleCI and they have an option for a SSH deployment. We should be able to run it on our own servers.

**Comment by polyphem** [comment]
SSH seems not to work (Operation timed out).

**Comment by wittenator** [comment]
@polyphem Could you work that out? I guess that you need to contact ZEDAT in order to resolve that. (As far as I remember you need to hop around a bit in order to get onto the server.)

**Comment by polyphem** [comment]
Server is in a DMZ and can't be reached directly (guide in confluence).

**Comment by ckinkeldey** [comment]
nginx: restrict to subnet of FU Berlin

**Comment by polyphem** [comment]
Create a acc on https://hub.docker.com and push the images.

**Comment by ckinkeldey** [comment]
Could we protect it with a htaccess password?

**Comment by ckinkeldey** [comment]
Die Technik schreibt:
Am 2020-02-18 13:41:58, christoph.kinkeldey@fu-berlin.de schrieb:

was Tim gerade am Telefon erwähnte, hier die Adressen, auf die wir
zugreifen müssen:

https://github.com <https://github.com/>

docker.pkg.github.com (http / https)

https://via.naturkundemuseum.berlin
<https://via.naturkundemuseum.berlin/>

https://nominatim.openstreetmap.org
<https://nominatim.openstreetmap.org/>

geht jetzt alles von 'ikon-research' AKA 'aghcc-srv06' aus...

Achtung: Die IPs der ersten beiden wechseln häufig. Falls es also irgendwann *nicht* geht, bitte

   nslookup github.com

bzw.

   nslookup docker.pkg.github.com

auf ikon-research aufrufen und schauen, ob die IP, die dann angezeigt wird, noch nicht in der jetzigen Liste

                       github.com has address 140.82.118.3
                       github.com has address 140.82.118.4
                       github.com has address 192.30.252.129
                       github.com has address 192.30.252.130
                       github.com has address 192.30.252.131
                       github.com has address 192.30.252.128
                       github.com has address 192.30.253.112
                       github.com has address 192.30.253.113


bzw.
                       docker.pkg.github.com is an alias for pkg.github.com.
                       pkg.github.com has address 140.82.114.34
                       pkg.github.com has address 192.30.253.164
                       pkg.github.com has address 192.30.253.165

enthalten ist. 

Falls sie *nicht* drin sein sollte, bitte uns einen entsprechenden Hinweis und die IP mailen, dann tragen wir die Ergänzung auf der Firewall nach.

(Die nächste Firewall soll das *dynamisch* selbst auflösen bzw. aktualisieren können. Die jetzige kann das noch nicht.)

**Comment by wittenator** [comment]
Is there any update from Ingmar?
