### ISSUE TITLE
Add automated OpenAPI documentation

### ISSUE THREAD

**Issue by wittenator** [FUB-HCC/IKON-backend#50]
**Is your feature request related to a problem? Please describe.**
The documentation for the backend is not up-to-date or missing completly.

**Describe the solution you'd like**
The API documentation should be autogenerated from the express router middleware and served on an endpoint.

**Comment by ckinkeldey** [comment]
Plese make API docs available under [url]/docs

**Comment by wittenator** [comment]
Solved and documented in README
