### ISSUE TITLE
VIA data in DB

### ISSUE THREAD

**Issue by ckinkeldey** [FUB-HCC/IKON-backend#71]
DB should get:

- [x] projects from VIA
- [x] KTAs from VIA
- [x] KTA target groups from VIA
- [x] KTA formats from VIA
- [x] collections from VIA
- [x] infrastructures from VIA
- [x] check links between KTAs / projects / collections / infrastructures
- [x] atomize "participating_subject_areas", left of first "/": remains; middle string -> "review_board"

**Comment by jessebenjamin** [comment]
whats the status?

**Comment by jessebenjamin** [comment]
*bump*
