### ISSUE TITLE
Kurzdoku: Test Kommunikation Backend <-> Wiki

### ISSUE THREAD

**Issue by ckinkeldey** [FUB-HCC/IKON-backend#74]
Alvaro möchte auf deren Server probieren, ob unser Backend die Daten vom MediaWiki ziehen kann (in der künftigen Infrastruktur). Dafür braucht er eine kurze Doku, die beschreibt, wie er sieht, ob es geklappt hat (Logs / CSVs in assets?)

**Comment by wittenator** [comment]
Wenn https://localhost:5434/projects eine gültige JSON zurückgibt, funktioniert alles. Alternativ wenn die Logs vom MWC Service keine Fehlermeldung wirft.

**Comment by jessebenjamin** [comment]
perfekt! schreib das mal dick und fett als Test-Verfahren in das entsprechende Readme bitte

**Comment by alvarosaurus** [comment]
Es soll möglich sein, ohne Vorkenntnisse des Projekts testen zu können, ob die installierte Software funktioniert. Also brauche ich keinesfalls eine "Kurzdoku", womit ich etwas "ausprobieren" kann, sondern ein oder mehrere **Unit Tests**.

Priorität superhoch. Keine Tests = keine Abnahme

**Comment by jessebenjamin** [comment]
@alvarosaurus ist es akzeptabel dass der test in eine (übersichtliche) datei geschrieben wird?

**Comment by alvarosaurus** [comment]
Solange die Datei ein ausführbares Skript ist ja, obwohl der Aufwand -für euch- geringer wäre, wenn der Test auf Basis eines gängigen Frameworks gebaut ist (wir benutzen Selenium).

(editiert, 30.08.2019)
Oder wie der Kollege von FB3 gesagt hat, auf Basis von Swagger 
https://swagger.io/tools/swagger-inspector/

**Comment by jessebenjamin** [comment]
What's the status?

**Comment by jessebenjamin** [comment]
*bump*
