### ISSUE TITLE
Security aspects

### ISSUE THREAD

**Issue by ckinkeldey** [FUB-HCC/IKON-backend#75]
What are possible security issues with the prototype?

**Comment by wittenator** [comment]
At the Moment:
*Problem:* MITM attacks on communication between services

*Information to gain:* It's possible to extract information from services (e.g. DB) or send malicious information

*Possible Fix:* Isolate Docker network

______________________________________________________________________________

*Problem:* Gaining access to the physical server 

*Information to gain:* It's possible to extract the credentials e.g. for the VIA wiki

*Possible Fix:* No real fix, hardening of the server infrastructure could help

**Comment by jessebenjamin** [comment]
Alvaro requested an assessment on user data (logging etc) as well? htaccess was mentioned as well

**Comment by wittenator** [comment]
What does "assessment on user data" mean? Since the whole docker network will be proxied by the museum either way, I would propose that they create a htaccess file tailored to their own infrastructure and intraorganizational processes. (Which we do not have access to atm.)

**Comment by alvarosaurus** [comment]
We could do as wittenator suggests, that's the solution we have discussed before. It should be possible for the prototype to mount the htaccess file from the host. Please specify e.g. in docker-compose, where these htaccess files should be.
