### ISSUE TITLE
SysAdmin Doc

### ISSUE THREAD

**Issue by jessebenjamin** [FUB-HCC/IKON-backend#76]
- [x] list of ports and what they serve
- [x] list of services, description and their interconnection
- [x] add architecture diagram (data/ports etc)

**Comment by jessebenjamin** [comment]
Please add this as a list to backend-readme, image + descriptions + list of ports (with note that this is the default setup and subject to change if implemented at MfN)

**Comment by jessebenjamin** [comment]
what's the status?

**Comment by polyphem** [comment]
https://github.com/FUB-HCC/IKON/wiki/Containerization-and-Docker

**Comment by jessebenjamin** [comment]
@alvarosaurus please review

**Comment by alvarosaurus** [comment]
Es heisst definitiv "Containerization", nicht "Containerism".

"To deliver software packages efficiently, we use docker". Was menst du mit "efficiently"? War es nicht eher so, dass Docker eine Anforderung vom MfN-IT war? Wenn ich mich richtig erinnnere, hätte Jonaz lieber Vagrant gehabt. Wie auch immer, es sollte klarer sein oder weg.

"Docker" soll capitalisiert werden, auch auf English.

"encapsulated", nicht "capsule" (wenn die Bezeichnung überhaupt korrekt ist)

"Among other things, it is mainly responsible for the clustering." nicht verständlich. Welche "other things"? Was ist mit "clustering" gemeint?

Im Diagramm heisst es "Visualisation", im Text "visualization", bitte entscheidet euch für US oder UK Rechtschreibung.

Da es schon mal Probleme mit Zertifikate gab, bitte auch die Zertifikate dokumentieren.

Kann ich das Backend und Frontend ausprobieren? Wie tue ich das? Bitte verlinken.

**Comment by polyphem** [comment]
@alvarosaurus  Danke für dem Input. Geht es um SSL Zertifikate?

**Comment by polyphem** [comment]
Das Front-End kann am Ende genau wie die anderen Container mit docker-compose gestartet werden.

**Comment by alvarosaurus** [comment]
Nach Absprache mit dem Webadmin kriegt ihr VPN-Zugang auf einem dedizierten Server am Museum, und könnt euer Ding selber installieren, wenn ihr so weit seid. NB der Server wurde in Mai 2019 für euch aufgesetzt, sieh Protokoll 2019-05-21+Development+Arbeitstreffen

@jessebenjamin please review
