### ISSUE TITLE
[URGENT] SysDoc Deadline (07.10.)

### ISSUE THREAD

**Issue by jessebenjamin** [FUB-HCC/IKON-backend#84]
As pages in IKON Wiki:

- [x] Nicolo: List possible Maintenance Requirements
- [x] Tim: List Server Requirements (also GPU)
- [x] Nicolo: List Postman-Queries for Container-Endpoints

**Comment by wittenator** [comment]
- as many cores as possible
- atleast 8 Gbs of RAM at all times, but the more the better
- 2 Gb harddrive space
- a GPU would only speed up the training

**Comment by jessebenjamin** [comment]
as wiki pages here please: https://github.com/FUB-HCC/IKON

also please expand with the settings we asked of our IT, i.e., the current setup. should be in an email
